version: "3"

services:
  web:
    build: ./
    image: kostarelo/slackzones
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - "./app:/src/app"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
